version: '1'

services:
	Service 1:
		build:
			context: ./Service1
			docker-file: dockerfile

	Service 2A:
		build:
			context: ./Service2/namegen
			docker-file: dockerfile

	Service 3A:
		build:
			context: ./Service3/statsgen
			docker-file: dockerfile

	Service 4A:
		build:
			context: ./Service4/application
			docker-file: dockerfile

	Service 2B:
		build:
			context: ./Service2/namegenB   
			docker-file: dockerfile

	Service 3B:
		build:
			context: ./Service3/statsgenB
			docker-file: dockerfile

	Service 4B:
		build:
			context: ./Service4/application2       
			docker-file: dockerfile

